(()=>{
const c=document.getElementById('game'),x=c.getContext('2d'),W=c.width,H=c.height,C=31,R=17,T=36,OX=(W-C*T)/2,OY=(H-R*T)/2;
const $=id=>document.getElementById(id),scoreE=$('score'),highE=$('highScore'),levelE=$('level'),flagsE=$('flagsLeft'),panel=$('startPanel'),btn=$('startBtn'),msg=$('message');
const D={left:[-1,0,Math.PI],right:[1,0,0],up:[0,-1,-Math.PI/2],down:[0,1,Math.PI/2]},opp={left:'right',right:'left',up:'down',down:'up'};
let geo=null,run=0,score=0,level=1,lives=3,hi=+localStorage.aegeanManHigh||0,w=[],flags=new Map,storms=[],dir='right',queued='right',px=2,py=8,last=0,acc=0,particles=[];
const pad=(n,k)=>String(Math.max(0,n|0)).padStart(k,'0'),cx=a=>OX+a*T+T/2,cy=a=>OY+a*T+T/2,key=(a,b)=>a+','+b;
highE.textContent=pad(hi,5);
function walls(){w=Array.from({length:R},()=>Array(C).fill(0));for(let i=0;i<C;i++)w[0][i]=w[R-1][i]=1;for(let i=0;i<R;i++)w[i][0]=w[i][C-1]=1;[[5,2,1,4],[5,8,1,6],[9,1,1,5],[9,8,1,3],[9,13,1,3],[13,3,1,4],[13,9,1,6],[17,1,1,4],[17,7,1,4],[17,13,1,3],[21,3,1,5],[21,10,1,5],[25,1,1,5],[25,8,1,6],[3,6,5,1],[11,7,5,1],[19,8,5,1],[23,6,5,1],[2,12,4,1],[7,11,5,1],[14,5,4,1],[18,13,5,1],[26,12,3,1]].forEach(([a,b,q,z])=>{for(let j=b;j<b+z;j++)for(let i=a;i<a+q;i++)w[j][i]=1})}
const open=(a,b)=>a>0&&b>0&&a<C-1&&b<R-1&&!w[b][a];
function makeFlags(){flags.clear();for(let b=1;b<R-1;b++)for(let a=1;a<C-1;a++)if(open(a,b)&&!(a==2&&b==8)&&((a*13+b*17)%5==0))flags.set(key(a,b),[a,b,Math.random()*6.28]);flagsE.textContent=pad(flags.size,2)}
function makeStorms(){storms=[];[[28,3,'left'],[15,14,'up'],[11,4,'right'],[23,14,'left']].slice(0,Math.min(2+(level>>1),4)).forEach(([a,b,d])=>{while(!open(a,b))a--;storms.push({a,b,d,t:0})})}
function hud(){scoreE.textContent=pad(score,5);highE.textContent=pad(Math.max(score,hi),5);levelE.textContent=pad(level,2);flagsE.textContent=pad(flags.size,2)}
function note(s){msg.textContent=s;msg.classList.add('show');setTimeout(()=>msg.classList.remove('show'),1200)}
function burst(a,b,col){for(let i=0;i<12;i++){let q=Math.random()*6.28,v=40+Math.random()*90;particles.push({x:a,y:b,vx:Math.cos(q)*v,vy:Math.sin(q)*v,l:.5+Math.random()*.4,c:col})}}
function start(){score=0;level=1;lives=3;px=2;py=8;dir=queued='right';walls();makeFlags();makeStorms();hud();run=1;panel.classList.remove('panel-visible');note('LEVEL 01 · BOSS MODE')}
function over(){run=0;if(score>hi){hi=score;localStorage.aegeanManHigh=hi}hud();let q=panel.querySelector('.panel-card');q.querySelector('.badge').textContent='RUN COMPLETE';q.querySelector('h2').textContent='Boss level got you.';q.querySelector('p').textContent='Score '+pad(score,5)+' · Level '+pad(level,2)+'. The Aegean is still waiting.';btn.textContent='PLAY AGAIN';panel.classList.add('panel-visible')}
function next(){level++;score+=1000*level;px=2;py=8;dir=queued='right';makeFlags();makeStorms();hud();note('LEVEL '+pad(level,2)+' · HARDER')}
function move(){if(!run)return;let q=D[queued];if(open(px+q[0],py+q[1]))dir=queued;let d=D[dir];if(open(px+d[0],py+d[1])){px+=d[0];py+=d[1]}let k=key(px,py);if(flags.has(k)){flags.delete(k);score+=100+level*15;burst(cx(px),cy(py),'#69e6ff');hud();if(!flags.size)next()}for(let s of storms){if(s.a==px&&s.b==py){lives--;burst(cx(px),cy(py),'#ff4d5e');px=2;py=8;if(lives<=0)over();else note('STORM HIT · '+lives+' LIVES LEFT');break}}}
function stormMove(){for(let s of storms){let opts=Object.keys(D).filter(n=>{let d=D[n];return n!=opp[s.d]&&open(s.a+d[0],s.b+d[1])});if(!opts.length)opts=[opp[s.d]];if(!opts.includes(s.d)||Math.random()<.3)s.d=opts[Math.random()*opts.length|0];let d=D[s.d];if(open(s.a+d[0],s.b+d[1])){s.a+=d[0];s.b+=d[1]}}}
function map(){if(!geo)return;for(let f of geo.features){let g=f.geometry,p=g.type=='MultiPolygon'?g.coordinates:[g.coordinates];x.beginPath();for(let poly of p)for(let ring of poly)ring.forEach((v,i)=>{let X=(v[0]-19)/12.2*W,Y=(42.5-v[1])/8.3*H;i?x.lineTo(X,Y):x.moveTo(X,Y)});let tr=f.properties.side=='TR';x.fillStyle=tr?'rgba(118,58,68,.28)':'rgba(52,79,110,.28)';x.strokeStyle=tr?'rgba(255,104,112,.42)':'rgba(112,190,255,.42)';x.lineWidth=1;x.fill('evenodd');x.stroke()}x.font='800 13px system-ui';x.fillStyle='rgba(190,220,240,.43)';x.fillText('GREECE',170,290);x.fillText('TÜRKİYE',990,325);x.fillStyle='rgba(105,230,255,.3)';x.fillText('A E G E A N   S E A',525,370)}
function greek(a,b,s=1){let q=20*s,z=14*s,A=a-q/2,B=b-z/2;x.save();x.shadowColor='#58b7ff';x.shadowBlur=7;x.fillStyle='white';x.fillRect(A,B,q,z);x.fillStyle='#1769aa';let h=z/9;for(let i=0;i<9;i+=2)x.fillRect(A,B+i*h,q,h+.2);let m=z*5/9;x.fillRect(A,B,m,m);x.fillStyle='white';x.fillRect(A+m*.4,B,m*.2,m);x.fillRect(A,B+m*.4,m,m*.2);x.restore()}
function star(a,b,r){x.beginPath();for(let i=0;i<10;i++){let q=i%2?r:r*.42,t=-Math.PI/2+i*Math.PI/5,A=a+Math.cos(t)*q,B=b+Math.sin(t)*q;i?x.lineTo(A,B):x.moveTo(A,B)}x.closePath();x.fill()}
function player(t){x.save();x.translate(cx(px),cy(py));x.rotate(D[dir][2]);let m=.2+Math.abs(Math.sin(t*.012))*.12;x.shadowColor='#ff4452';x.shadowBlur=22;x.beginPath();x.moveTo(0,0);x.arc(0,0,15,m,6.28-m);x.closePath();x.fillStyle='#e92f3c';x.fill();x.rotate(-D[dir][2]);x.fillStyle='white';x.beginPath();x.arc(-2,0,7.3,0,6.28);x.fill();x.fillStyle='#e92f3c';x.beginPath();x.arc(1.3,-.5,6.5,0,6.28);x.fill();x.fillStyle='white';star(6,0,3.5);x.restore()}
function draw(t){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#07192b');g.addColorStop(1,'#030a13');x.fillStyle=g;x.fillRect(0,0,W,H);map();for(let b=0;b<R;b++)for(let a=0;a<C;a++)if(w[b][a]){x.fillStyle='rgba(3,11,22,.68)';x.strokeStyle='rgba(95,212,247,.18)';x.beginPath();x.roundRect(OX+a*T+3,OY+b*T+3,T-6,T-6,10);x.fill();x.stroke()}for(let f of flags.values())greek(cx(f[0]),cy(f[1]),.82+Math.sin(t*.004+f[2])*.1);for(let s of storms){x.save();x.translate(cx(s.a),cy(s.b));x.rotate(t*.004+s.a);x.strokeStyle='#c066ff';x.lineWidth=4;x.shadowColor='#c066ff';x.shadowBlur=18;for(let i=0;i<3;i++){x.beginPath();x.arc(0,0,9+i*5,i,Math.PI*1.2+i);x.stroke()}x.restore()}player(t);for(let p of particles){x.globalAlpha=Math.max(0,p.l*2);x.fillStyle=p.c;x.beginPath();x.arc(p.x,p.y,2.5,0,6.28);x.fill()}x.globalAlpha=1;x.font='800 11px system-ui';x.fillStyle='rgba(220,235,245,.65)';x.fillText('LIVES',24,32);for(let i=0;i<3;i++){x.fillStyle=i<lives?'#ef3340':'rgba(255,255,255,.12)';x.beginPath();x.arc(30+i*18,50,5.5,0,6.28);x.fill()}let v=x.createRadialGradient(W/2,H/2,100,W/2,H/2,W*.65);v.addColorStop(0,'transparent');v.addColorStop(1,'rgba(0,0,0,.5)');x.fillStyle=v;x.fillRect(0,0,W,H)}
function loop(t){let dt=Math.min(.05,(t-last)/1000||0);last=t;if(run){acc+=dt;if(acc>.11){move();acc=0}storms.forEach(s=>s.t+=dt);if(storms[0]&&storms[0].t>.34){stormMove();storms.forEach(s=>s.t=0)}}for(let p of particles){p.l-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=35*dt}particles=particles.filter(p=>p.l>0);draw(t);requestAnimationFrame(loop)}
document.addEventListener('keydown',e=>{let m={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'};if(m[e.key]){e.preventDefault();queued=m[e.key]}if((e.key==' '||e.key=='Enter')&&!run)start()},{passive:false});document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();queued=b.dataset.dir},{passive:false}));btn.onclick=start;
walls();makeFlags();makeStorms();fetch('./aegean-map.json').then(r=>r.json()).then(j=>geo=j).catch(()=>0);requestAnimationFrame(loop);
})();
